### ISSUE TITLE
Fail to install Storeman on SailfishOS 4.4.0 due to missing `libsolv0`

### ISSUE THREAD

**Issue by explit7** [storeman-developers/harbour-storeman#160]
I updated to the latest cbeta-version (4.4.0.49) and see now, that my storeman is removed during the installation.
If i start the harbour-storeman-installation icon - nothing happens.

```
The latest rpm harbour-storeman-0.2.8-2.sdk4.1.0.24.armv7hl.rpm could also not installed:

Problem: nothing provides 'libsolv0' needed by the to be installed harbour-storeman-0.2.8-2~sdk4.1.0.24.armv7hl
 Solution 1: do not install harbour-storeman-0.2.8-2~sdk4.1.0.24.armv7hl
 Solution 2: break harbour-storeman-0.2.8-2~sdk4.1.0.24.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

**Comment by Olf0** [comment]
`libsolv0` is central to Storeman's functioning.  This might be an error on Jolla's side.  Do you have access to a changelog, so you can check if the missing `libsolv0` is really intended?

**Comment by Olf0** [comment]
> The latest rpm harbour-storeman-0.2.8-2.sdk4.1.0.24.armv7hl.rpm …

The recent Storeman version is 0.2.11

As the Installer fails for you, download the latest Storeman 0.2.11 from https://build.sailfishos.org/package/show/home:mentaljam/harbour-storeman
I.e. for your CPU-architecture (armv7hl) on SFOS 4.3.0: https://repo.sailfishos.org/obs/home:/mentaljam/4.3.0.12_armv7hl/armv7hl/harbour-storeman-0.2.11+sfos4.2.20210918134855.2.g1945da7-1.34.1.jolla.armv7hl.rpm
Install it via filemanager or `pkcon install-local harbour-storeman-0.2.11+sfos4.2.20210918134855.2.g1945da7-1.34.1.jolla.armv7hl.rpm`

**Comment by explit7** [comment]
thanks, will try!

**Comment by explit7** [comment]
![Screenshot from 2022-03-12 13-01-59](https://user-images.githubusercontent.com/11852348/158017199-f55ba51e-e206-41a5-8b4b-d514f67dddba.png)

**Comment by explit7** [comment]
unfortunately, it still throws an libsolv0 dependence error on 4.4.0.50

**Comment by mentaljam** [comment]
@explit7, could you please search for libsolv packages on your SFOS version? This library is used by libzypp and could not be just removed. Maybe its name was changed and we need to patch the spec file

**Comment by explit7** [comment]
```
Information for package libsolv:
--------------------------------
Repository     : jolla
Name           : libsolv
Version        : 0.7.20+git1-1.6.2.jolla
Arch           : armv7hl
Vendor         : meego
Installed Size : 304.1 KiB
Installed      : Yes
Status         : up-to-date
Source package : libsolv-0.7.20+git1-1.6.2.jolla.src
Summary        : A new approach to package dependency solving
Description    : 
    A new approach to package dependency solving.
```

**Comment by explit7** [comment]
`[root@XA2P-H4493 lib]# ls -la libsolv*
lrwxrwxrwx    1 root     root            21 Feb 20 00:17 libsolv.so.0 -> /usr/lib/libsolv.so.1
-rwxr-xr-x    1 root     root        384800 Feb 14 03:34 libsolv.so.1
-rwxr-xr-x    1 root     root        146356 Feb 14 03:34 libsolvext.so.1
`

**Comment by Olf0** [comment]
It was Jolla (as usual), see https://github.com/sailfishos/libsolv/commit/da1de8e045f6024447b47abea59d4a714fcdf7a5#diff-9b855f67079ea66ba4fabfd5e3f2150d548434ef885086842f66ebdb5674d442L25-L26

Will fix that in the next release.  But that may take a while.  Until then, please install manually with `rpm -i --nodeps`

**Comment by Olf0** [comment]
Informational: I checked that `libsolv0` was merely an alias to `libsolv` on SailfishOS 2.2.1 and 3.2.1.  As SailfishOS 2.1.4 is the minimal release supported by Storeman's current code, I hope this is fine for 2.1.4 and 2.2.0, which I cannot check.

**Comment by Olf0** [comment]
@explit7, can you please test on SFOS 4.4.4 (and if you like on devices with older SFOS releases, too):
* At least on one device: Remove ("uninstall") Storeman to test the Storeman Installer.
  * Download Storeman Installer v1.2.0 from [the SailfishOS-OBS](https://build.sailfishos.org/package/show/home:olf:harbour-storeman/harbour-storeman-installer) or [its GitHub release section](https://github.com/storeman-developers/harbour-storeman-installer/releases).
  * Install it per file-manager (needs "untrusted sources" enabled in SFOS Settings app) or per `pkcon install-local <full-rpm-filename>`
  * Use it to install Storeman v0.2.12
  * Use Storeman: Not necessarily for installing or removing packages, but please visit each page of it.
  * Report success or failure here.
* On additional devices you may simply update Storeman:
  * Download Storeman v0.2.12 from [the SailfishOS-OBS](https://build.sailfishos.org/package/show/home:olf:harbour-storeman) or [its GitHub release section](https://github.com/storeman-developers/harbour-storeman/releases).
  * Install it per file-manager (needs "untrusted sources" enabled in SFOS Settings app) or per `pkcon install-local <full-rpm-filename>`
  * Use Storeman: Not necessarily for installing or removing packages, but please visit each page of it.
  * Report success or failure here.

Thanks!

**Comment by explit7** [comment]
Tested on Xperia XA2 4.4.0.50 and 4.4.0.58 Works without any Problems

**Comment by szopin** [comment]
On jolla C 4.4 endless Initialising after installing through terminal as per the guidance

**Comment by Olf0** [comment]
> On jolla C 4.4 endless Initialising after installing through terminal as per the guidance

@szopin, please open a *new* issue using the [bug report template](https://github.com/storeman-developers/harbour-storeman-installer/issues/new?assignees=&labels=bug&template=bug-template.md&title=%5BBug%5D+) and include the output of `harbour-storeman` being started at the command line.

This issue is resolved and hence closed.

**Comment by explit7** [comment]
> On jolla C 4.4 endless Initialising after installing through terminal as per the guidance (this is on a device fresh from factory reset and all the updates from 2.0.x->4.4 with backup restore at 4.3, adding repos not possible)

@szopin Just add this 2 lines to /usr/share/applications/harbour-storeman.desktop

`[X-Sailjail]
Sandboxing=Disabled
`

**Comment by szopin** [comment]
@explit7 Thanks, that worked!

**Comment by Thaodan** [comment]
Why was there an explicit dependency in the first place? RPM will scan for the binary dependency and it to to the Requires: section.
The output of rpmlint will show this.

**Comment by Olf0** [comment]
> Why was there an explicit dependency in the first place? 

I don't know for sure, but I assume an explicit dependency on `libsolv0` was once needed.

> RPM will scan for the binary dependency and it to to the Requires: section. The output of rpmlint will show this.

It does, I have not had the time to ever look at it, yet.
```
harbour-storeman.armv7hl: E: explicit-lib-dependency libsolv
You must let rpm find the library dependencies by itself. Do not put unneeded explicit Requires: tags.
```
So you are suggesting to simply drop the explicit dependency on `libsolv` / `libsolv0`?
I wonder why `rpmlint` calls this an *error* for `libsolv` (on SFOS 4.2+), but only a *warning* for `libsolv0` (on earlier SFOS releases, e.g. 3.1.0)?  There seems to be some difference.

**Comment by Thaodan** [comment]
> > Why was there an explicit dependency in the first place?
> 
> I don't know for sure, but I assume @mentaljam once decided that an explicit dependency on `libsolv0` was needed.
> 
> > RPM will scan for the binary dependency and it to to the Requires: section. The output of rpmlint will show this.
> 
> It does, thanks for the hint; I have not had the time to ever look at it before.
> 
> ```
> harbour-storeman.armv7hl: E: explicit-lib-dependency libsolv
> You must let rpm find the library dependencies by itself. Do not put unneeded
> explicit Requires: tags.
> ```
> 
> So you are suggesting to simply drop the explicit dependency on `libsolv` / `libsolv0`?
Yes, use pkgconfig() BuildRequires: instead to avoid issues when the package name changes.

 I wonder why `rpmlint` calls this an _error_ for `libsolv` (when compiled for SFOS 4.2+), but only a _warning_ for `libsolv0` (when compiled for earlier SFOS releases, e.g., 3.1.0)? There seems to be some difference:
> 
> ```
> harbour-storeman.armv7hl: W: explicit-lib-dependency libsolv0
> You must let rpm find the library dependencies by itself. Do not put unneeded
> explicit Requires: tags.
> ```
I'd guess different rpmlint settings. I didn't check exactly.

**Comment by Olf0** [comment]
> I'd guess different rpmlint settings. I didn't check exactly.

As I avoid doing anything locally, the quotes were from the `rpmlint` runs at the Sailfish-OBS, see [for SFOS4.2+](https://build.sailfishos.org/package/show/home:olf:harbour-storeman/harbour-storeman-sfos4.2), [for SFOS3.3+](https://build.sailfishos.org/package/show/home:olf:harbour-storeman/harbour-storeman-sfos3.3) and [for SFOS3.1+](https://build.sailfishos.org/package/show/home:olf:harbour-storeman/harbour-storeman-sfos3.2).  I have no idea how to check `rpmlint`'s setting there.

**Comment by Olf0** [comment]
> > I wonder why `rpmlint` calls this an _error_ for `libsolv` (when compiled for SFOS 4.2+), but only a _warning_ for `libsolv0` (when compiled for earlier SFOS releases, e.g., 3.1.0)? There seems to be some difference: […]
> 
> I'd guess different rpmlint settings. I didn't check exactly.

Yes, the "download on demand (DoD)"-repositories at the SailfishOS-OBS provide different `rpmlint` versions: The newer ones have a stricter configuration, marking some former warnings as errors.

**Comment by Olf0** [comment]
> > So you are suggesting to simply drop the explicit dependency on libsolv / libsolv0?
> 
> Yes, use pkgconfig() BuildRequires: instead to avoid issues when the package name changes.

<sup>The quoting was garbled, hence I did not see that before!</sup>
So you are suggesting to use an `BuildRequires: pkgconfig(libsolv)` in addition to the extant [build dependency on `libsol-devel`](https://github.com/storeman-developers/harbour-storeman/blob/devel/rpm/harbour-storeman.spec#L30)?

**Comment by Olf0** [comment]
> > > So you are suggesting to simply drop the explicit dependency on libsolv / libsolv0?
> > 
> > Yes, use pkgconfig() BuildRequires: instead to avoid issues when the package name changes.
> 
> Are you suggesting to use an `BuildRequires: pkgconfig(libsolv)` in addition to the extant [build dependency on `libsolv-devel`](https://github.com/storeman-developers/harbour-storeman/blob/devel/rpm/harbour-storeman.spec#L30)?

@mentaljam, can you confirm that I understood @Thaodan correctly and that this is the right thing to do?

**Comment by Olf0** [comment]
@Thaodan, please provide a proper advice.  Your statements
> > RPM will scan for the binary dependency and it to to the Requires: section.

and
> > That doesn't matter it is always bad do have explicit-lib-dependencies just fix it for all versions..

plus your "hidden" message (due to incorrect quoting)
> > > So you are suggesting to simply drop the explicit dependency on libsolv / libsolv0?
> > Yes, use pkgconfig() BuildRequires: instead to avoid issues when the package name changes.

leave room for interpretation.
Please write some concise statement or simply answer my already posed question:
> Are you suggesting to use a `BuildRequires: pkgconfig(libsolv)` in addition to the extant [build dependency on `libsolv-devel`](https://github.com/storeman-developers/harbour-storeman/blob/devel/rpm/harbour-storeman.spec#L30)?

{Yes|No}?

Without this your efforts are futile, because they are incomprehensible for me.

**Comment by Thaodan** [comment]
> > Are you suggesting to use a `BuildRequires: pkgconfig(libsolv)` in addition to the extant [build dependency on `libsolv-devel`](https://github.com/storeman-developers/harbour-storeman/blob/devel/rpm/harbour-storeman.spec#L30)?
> 
> {Yes|No}?

Didn't had time to reply until now. BuildRequires; libsolv-devel is fine, pkgconfig(libsolv) is a little better but no need for both.

**Comment by Olf0** [comment]
@Thaodan, thank you for your reply.

I tried to figure this out by myself in the past three weeks, but the `pkg-config` [man page](https://linux.die.net/man/1/pkg-config), [documentation](https://www.freedesktop.org/wiki/Software/pkg-config/) and [tutorial](http://people.freedesktop.org/~dbn/pkg-config-guide.html) does not cover this use case at all, while `pkkconf` only provides documentation for [further developing it](https://github.com/pkgconf/pkgconf/tree/master/doc) and simply states that [it is fully compatible to `pkg-config`](https://github.com/pkgconf/pkgconf#compatibility-with-pkg-config).

Ultimately I found on Fedora Docs the [Packaging Guidelines / Pkgconfig Build Dependencies](https://docs.fedoraproject.org/en-US/packaging-guidelines/PkgConfigBuildRequires/), which explain exactly what you wrote, while [this Stackexchange thread](https://unix.stackexchange.com/questions/592437/how-does-pkg-config-work-in-rpm-specfiles) and [this article](https://www.dvratil.cz/2015/03/fedora-rpm-automatic-provides-for-cmake-projects-packages/) further support this (the latter also for `cmake`, which is quite interesting).

But all this seems to be unrelated to this issue #160!  This was about a `Requires:  libsolv0` line, not about `BuildRequires:  libsolv-devel`.  Or am I missing something?

**Comment by Thaodan** [comment]
> I tried to figure this out by myself in the past three weeks, but the `pkg-config` [man page](https://linux.die.net/man/1/pkg-config), [documentation](https://www.freedesktop.org/wiki/Software/pkg-config/) and [tutorial](http://people.freedesktop.org/~dbn/pkg-config-guide.html) does not cover this use case at all, while `pkkconf` only provides documentation for [further developing it](https://github.com/pkgconf/pkgconf/tree/master/doc) and simply states that [it is fully compatible to `pkg-config`](https://github.com/pkgconf/pkgconf#compatibility-with-pkg-config).

The pkgconfig symbol does not have anything directly to do with pkgconf or pkg-config. Any of those can be used to scan package for symbols that are either require or provided (read https://github.com/rpm-software-management/rpm/blob/master/scripts/pkgconfigdeps.sh).

>But all this seems to be unrelated to this issue https://github.com/storeman-developers/harbour-storeman/issues/160! This was about a Requires: libsolv0 line, not about BuildRequires: libsolv-devel. Or am I missing something?
This was already solved by 5627c9294313b367e35ff47b73e9e108c1be63a6, my commit d5fb252c56d32f0a1652782780e22eaa911c6269 relates to that this bug will not happen again when it comes to BuildRequires.

Also please don't reset the author patches/commit that are send!

**Comment by Olf0** [comment]
> > I tried to figure this out by myself in the past three weeks, but the `pkg-config` [man page](https://linux.die.net/man/1/pkg-config), [documentation](https://www.freedesktop.org/wiki/Software/pkg-config/) and [tutorial](http://people.freedesktop.org/~dbn/pkg-config-guide.html) does not cover this use case at all, while `pkkconf` only provides documentation for [further developing it](https://github.com/pkgconf/pkgconf/tree/master/doc) and simply states that [it is fully compatible to `pkg-config`](https://github.com/pkgconf/pkgconf#compatibility-with-pkg-config).
> 
> The pkgconfig symbol does not have anything directly to do with pkgconf or pkg-config. Any of those can be used to scan package for symbols that are either require or provided (read https://github.com/rpm-software-management/rpm/blob/master/scripts/pkgconfigdeps.sh).

Thank you for pointing out that this a feature of `rpm`.  Still I seem to miss a lot of context, 
> 
> > But all this seems to be unrelated to this issue #160! This was about a Requires: libsolv0 line, not about BuildRequires: libsolv-devel. Or am I missing something?
> 
> This was already solved by [5627c92](https://github.com/storeman-developers/harbour-storeman/commit/5627c9294313b367e35ff47b73e9e108c1be63a6), 

No, not "solved", I just omitted this dependency, because obviously `libsolv` is always installed on SFOS.  But this is not a correct solution, because Storeman *does* depend on `libsolv`; this is why @mentaljam origoinally defined this dependency.

Hence I still do not comprehend how to define a runtime dependency on `libsolv`, which works for all SFOS releases from 3.2.0 to 4.4.0.

Or do I have to introduce a release-branch specific dependency on `libsolv0` rsp. `libsolv`?

> my commit [d5fb252](https://github.com/storeman-developers/harbour-storeman/commit/d5fb252c56d32f0a1652782780e22eaa911c6269) relates to that this bug will not happen again when it comes to BuildRequires.

Thank you for finally clarifying that the change `BuildRequires:  libsolv-devel` → `BuildRequires:  pkgconf(libsolv)` completely unrelated to this issue.

> Also please don't reset the author patches/commit that are send!

Oops, I do not comprehend what "reset" means here.  I squash-merged your three commits, is that what you are addressing?  Or that I reverted the change `%setup -q` → `%autosetup`, which was part of one of these commits, because it provides no benefits?

Look, I change as little as I can, when I do not fully comprehend all possible implications and side-effects, because I lack the time and motivation to resolve resulting issues.  As I never used `%autosetup` and it seems to provide no advantage over `%setup` here (you only named "being cleaner" without describing a benefit), it had to go.

If you want to become a maintainer of Storeman, then such a change is sure O.K., because you would have the responsibility to deal with the resulting fall-out.  And this would enable me to reduce my efforts to what I originally offered: quality assurance / reviewing commits, issue handling and infrastructure.

**Comment by Olf0** [comment]
#### Notes to myself

But it seems that one has to know or [explicitly determine which packages provide `.pc` files in the build environment](https://www.pclinuxos.com/forum/index.php/topic,103882.msg1141748.html#msg1141748), in order to [use `pkgconfig(name)`](https://wiki.mageia.org/en/Packaging_guidelines#BuildRequires).

It seems that "symbol" is another heavily overloaded IT-term, there seems to be [a concept of "rpm symbols", which are symbolic names of packages (excellent guide)](https://documentation.suse.com/sbp/all/html/SBP-RPM-Packaging/index.html#sec-dependency), in contrast to the classic meaning of "exported entry point of a function in a complied library".

Side note: One should also check that the packages listed by `pkg-config --list-all` [have `pkg-config` defined as a runtime dependency](https://en.opensuse.org/openSUSE:Specfile_guidelines#Development_files).  [OpenSUSE and Fedora / RHEL seems to guarantee this for the packages they provide](https://github.com/juhp/cabal-rpm/issues/28).

**Comment by Thaodan** [comment]
> > > I tried to figure this out by myself in the past three weeks, but the `pkg-config` [man page](https://linux.die.net/man/1/pkg-config), [documentation](https://www.freedesktop.org/wiki/Software/pkg-config/) and [tutorial](http://people.freedesktop.org/~dbn/pkg-config-guide.html) does not cover this use case at all, while `pkkconf` only provides documentation for [further developing it](https://github.com/pkgconf/pkgconf/tree/master/doc) and simply states that [it is fully compatible to `pkg-config`](https://github.com/pkgconf/pkgconf#compatibility-with-pkg-config).
> > 
> > 
> > The pkgconfig symbol does not have anything directly to do with pkgconf or pkg-config. Any of those can be used to scan package for symbols that are either require or provided (read https://github.com/rpm-software-management/rpm/blob/master/scripts/pkgconfigdeps.sh).
> 
> Thank you for pointing out that this a feature of `rpm`. Still I seem to miss a lot of context, where and when this shell script is called. Never mind, I do not want to research this topic by reading source code (which is the best way to fully understand things, except for concepts / architectures; but a tedious one, and I lack time).

The script is called after the package is almost completely build when rpm scans the contents of the package with it requires or provides scanner. In this case it means that whenever a dependency that provides headers changes the pkgconfig symbol stays the same since it is upstream name of the software the scripts read the pkgconfig files and use the Name:  tag as the name of the symbol.
 
> > > But all this seems to be unrelated to this issue #160! This was about a Requires: libsolv0 line, not about BuildRequires: libsolv-devel. Or am I missing something?
> > 
> > 
> > This was already solved by [5627c92](https://github.com/storeman-developers/harbour-storeman/commit/5627c9294313b367e35ff47b73e9e108c1be63a6),
> 
> No, not "solved", I just omitted this dependency, because obviously `libsolv` is always installed on SFOS. But this is not a correct solution, because Storeman _does_ depend on `libsolv`; this is why @mentaljam originally defined this dependency.

It is because you should never specific dependencies any direct package names unless there's no other way, e.g. where there's no scanners such as for QML or -devel packages that don't provide cmake or pkgconfig symbols.
The Fedora packaging guidelines are a good read about this if you take into account that Sailfish OS not always has catched up with Fedora when it comes to recent development in rpm packaging.

> Hence I still do not comprehend how to define a runtime dependency on `libsolv`, which works for all SFOS releases from 3.2.0 to 4.4.0.
> 
> Or do I have to introduce a release-branch specific dependency on `libsolv0` rsp. `libsolv`?
RPM scans elf binaries for the symbols the require after the package is almost done building just like for pkgconf files.
When you require the required build dependencies the package builds and after that rpm finds the used shared libraries.
The end result is that a package is more robust against other changes such as renames or new libraries with different ABIs but have the same package name.  E.g. in case when libsolv breaks its ABI and is provide by another package that provides the old ABI libsolv0.

> > my commit [d5fb252](https://github.com/storeman-developers/harbour-storeman/commit/d5fb252c56d32f0a1652782780e22eaa911c6269) relates to that this bug will not happen again when it comes to BuildRequires.
> 
> Thank you for finally clarifying that the change `BuildRequires: libsolv-devel` → `BuildRequires: pkgconf(libsolv)` completely unrelated to this issue.
It is related for cases which I just described.

> > Also please don't reset the author patches/commit that are send!
> 
> Oops, I do not comprehend what "reset" means here. I squash-merged your three commits, is that what you are addressing? Or that I reverted the change `%setup -q` → `%autosetup`, which was part of one of these commits, because it provides no benefits?
I didn't saw the squash but I assume in this case Github just use you as the author without being the author.

> Look, I change as little as I can, when I do not fully comprehend all possible implications and side-effects, because I lack the time and motivation to resolve resulting issues. As I never used `%autosetup` and it seems to provide no advantage over `%setup` here (you only named "being cleaner" without describing a benefit), it had to go.
Then just drop commits, you revert commits it is just noise. I guess using Github webinterface has its limited in the cleanliness you want.

**Comment by Thaodan** [comment]
> It seems that "symbol" is another heavily overloaded IT-term, there seems to be [a concept of "rpm symbols", which are symbolic names of packages (excellent guide)](https://documentation.suse.com/sbp/all/html/SBP-RPM-Packaging/index.html#sec-dependency), in contrast to the classic meaning of "exported entry point of a function in a complied library".

The word is the same because in the case of rpm since it still describes the same thing for packages with binaries.
RPM expanded upon that to also provide symbols for language that don't really have exactly the same as ELF symbols.


> Side note: One should also check that the packages listed by `pkg-config --list-all` (in the build environment) [have `pkg-config` defined as a runtime dependency](https://en.opensuse.org/openSUSE:Specfile_guidelines#Development_files). [OpenSUSE and Fedora / RHEL seems to guarantee this for the packages they provide](https://github.com/juhp/cabal-rpm/issues/28).

zypper info --provides foobar-devel also works.

**Comment by Olf0** [comment]
**Back to the original issue**

A `rpm -qR harbour-storeman` with Storeman 0.3.0-5 installed shows `libsolv.so.0` among the derived ("injected"?) runtime dependencies, even though it is not defined as a dependency in the spec file.

I still do not understand why, but WTF: It does the right thing, although I hate such undocumented mysteries.

**Comment by Thaodan** [comment]
> **Back to the original issue**
> 
> A `rpm -qR harbour-storeman` with Storeman 0.3.0-5 installed shows `libsolv.so.0` among the derived ("injected"?) runtime dependencies (on SFOS 3.2.1), even though [it is not defined as a dependency in the spec file any more](https://github.com/storeman-developers/harbour-storeman/blob/sfos3.2/rpm/harbour-storeman.spec).
BuildRequires: pkgconfig(libsolv) installs libsolv-devel  that pulls  in libsolv. When the package is done building rpm uses objdump to find the libs used in all the binaries in storeman and adds Requires: libsolv.so.1(SOLV_1.0).

You can see that in the [buildlog](https://build.sailfishos.org/package/live_build_log/home:olf:harbour-storeman/harbour-storeman-sfos4.2/4.4.0.58_i486/i586)  after the line `[60s] Processing files: harbour-storeman-0.3.0-1.8.1.jolla.i486`.

**Comment by Olf0** [comment]
> BuildRequires: pkgconfig(libsolv) installs libsolv-devel that pulls in libsolv. When the package is done building rpm uses objdump to find the libs used in all the binaries in storeman and adds Requires: libsolv.so.1(SOLV_1.0).
> 

Thank you very much: This was the kind of concise explanation I hoped for throughout this thread.

> You can see that in the [buildlog](https://build.sailfishos.org/package/live_build_log/home:olf:harbour-storeman/harbour-storeman-sfos4.2/4.4.0.58_i486/i586) after the line `[60s] Processing files: harbour-storeman-0.3.0-1.8.1.jolla.i486`.

Thanks for the link: These seem to be many hidden sources of information at OBS, which cannot be reached by clicking through OBS's web-frontend.  Being able to access this build log is valuable.  Do you know of some documentation which lists such entry points to OBS (I assume there are more than this one, and the classic, hierarchical one)?

**Comment by Thaodan** [comment]
> > You can see that in the
> > [buildlog](https://build.sailfishos.org/package/live_build_log/home:olf:h
> > arbour-storeman/harbour-storeman-sfos4.2/4.4.0.58_i486/i586) after the
> > line `[60s] Processing files: harbour-storeman-0.3.0-1.8.1.jolla.i486`.
> Thanks for the link: These seem to be many hidden sources of information at
> OBS, which cannot be reached by clicking through OBS's web-frontend.  Being
> able to access this build log is valuable.  Do you know of some
> documentation which lists such entry points to OBS (I assume there are more
> than this one, and the classic, hierarchical one)?

All these are visible via the UI however maybe they are not that obvious.
E.g. You can see the build log of a package if you click on the build state of  
package.

You can inspect the resulting packages by clicking on the repostory name when 
viewing the package and then select an rpm file.
